version: '3'
services:
  app:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest 
    container_name: mongodb
    ports:
      - 27017:27017
    volumes: 
      - ./database-data:/data/db
  
  mongo-express:
    image: mongo-express:latest 
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "${ME_CONFIG_MONGODB_SERVER}"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
    depends_on:
      - mongodb

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: "${REDIS_HOSTS}"
    depends_on:
      - redis
